### ISSUE TITLE
Command not found on MacBook Air M1

### ISSUE THREAD

**Issue by jachen** [zuku/cusi#18]
Very promising script. But in my case the process completed and no chance to get cusi running.
I have a stickC plus connected at /dev/tty.usbserial-45525442E6. 

But:  $ cusi /dev/tty.usbserial-45525442E6 gives -> zsh: command not found: cusi

Any ideas?

**Comment by zuku** [comment]
@jachen 
If you don't put the command in a directory listed in `$PATH`, type `./cusi` instead of `cusi`.

```
% cd darwin_arm64
% ls
cusi
% cusi
zsh: command not found: cusi
% ./cusi
cusi is command line tools for M5Stack MicroPython system.

Usage: cusi [OPTION] [PORT]

  -h	display help
  -l	list serial ports
  -v	display version
```

**Comment by jachen** [comment]
So kind, Thanks a lot. I realize that I am missing some Basics. 
Have a good day!
